point_Info = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": 0.00,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": 0,
                        "BackPointRate": 30,
                        "BackMoneyRate": 0.00,
                        "backCashRate": 0.00,
                        "UserID": %s,
                        "UserName": "king158",
                        "InfoTitle": "测试资料",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": 0.00,
                    "SoftAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": 0.00,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": 0,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": 0.00,
                        "SoftPoint": 0,
                        "SoftPointConvertToRMB": %s,
                        "AdvPoint": 0,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": 4}'''

MoneyInfo = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": %s,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": %s,
                        "BackPointRate": 30,
                        "BackMoneyRate": %s,
                        "backCashRate": %s,
                        "UserID": %s,
                        "UserName": "mayanquan",
                        "InfoTitle": "测试资料为-%s",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": %s,
                    "SoftAsset": {
                        "SoftCash": %s,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": %s}'''

isSupplyInfo = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": %s,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": %s,
                        "BackPointRate": 30,
                        "BackMoneyRate": %s,
                        "backCashRate": %s,
                        "UserID": %s,
                        "UserName": "mayanquan",
                        "InfoTitle": "测试资料为-%s",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": %s,
                    "SoftAsset": {
                        "SoftCash": %s,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": %s}'''

thirdPartyInfo = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": %s,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": %s,
                        "BackPointRate": 30,
                        "BackMoneyRate": %s,
                        "backCashRate": %s,
                        "UserID": %s,
                        "UserName": "mayanquan",
                        "InfoTitle": "测试资料为-%s",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": %s,
                    "SoftAsset": {
                        "SoftCash": %s,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": %s}'''

scanCodeInfo = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": %s,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": %s,
                        "BackPointRate": 30,
                        "BackMoneyRate": %s,
                        "backCashRate": %s,
                        "UserID": %s,
                        "UserName": "mayanquan",
                        "InfoTitle": "测试资料为-%s",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": %s,
                    "SoftAsset": {
                        "SoftCash": %s,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": %s}'''

notSendRewardsInfo = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": %s,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": %s,
                        "BackPointRate": 30,
                        "BackMoneyRate": %s,
                        "backCashRate": %s,
                        "UserID": %s,
                        "UserName": "mayanquan",
                        "InfoTitle": "测试资料为-%s",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": %s,
                    "SoftAsset": {
                        "SoftCash": %s,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": %s}'''

notLevelInfo = '''{"eDownloadArgs": {
                    "eSoft": {
                        "ChannelID": 10,
                        "ClassID": 620,
                        "DepartmentID": 2,
                        "SoftVersion": "全国通用",
                        "SoftTypeID": 1,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.100,
                        "SoftMoney": %s,
                        "Hits": 16,
                        "Elite": false,
                        "Passed": true,
                        "IsSupply": %s,
                        "BackPointRate": 30,
                        "BackMoneyRate": %s,
                        "backCashRate": %s,
                        "UserID": %s,
                        "UserName": "mayanquan",
                        "InfoTitle": "测试资料为-%s",
                        "FileSize": 546,
                        "Censor": "数学卢正发",
                        "AdvPoint": 0,
                        "IsBoutique": 0,
                        "SourceID": 1,
                        "SoftCash": %s,
                    "SoftAsset": {
                        "SoftCash": %s,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "ConsumeAsset": {
                        "SoftCash": 0.00,
                        "SoftMoney": %s,
                        "SoftPoint": %s,
                        "SoftPointConvertToRMB": 0.200,
                        "AdvPoint": %s,
                        "AdvPointConvertToRMB": 0.0,
                        "Cash": 0.0,
                        "IsBoutique": 0,
                        "Type": 3,
                        "PriceStr": "点数:1.00 点",
                        "Price": 1.00,
                        "IsFree": false
                    },
                    "IsShowXkw": 0, 
                    "XkwSoftID": 0,
                    "EarnRmb": 0.0,
                    "EarnPoint": 0.0,
                    "GivePoint": 0,
                    "IsMonthPayed": false,
                    "InfoUpdays": 130,
                    "ZeroAndPointDownNum": 0,
                    "DownNumFeeBackType": 0,
                    "eDownloadCountInfo": null,
                    "SettlementLogPara": {
                        "IsUpdateDownloadHits": 0,
                        "IsIncrePoint": 0,
                        "FeeBackType": 0
                    },
                    "SoftID": %s,
                    "SoftName": "2018年武汉市",
                    "SoftSize": 546,
                    "FileAddress": "{ploaddir}2019-2/24/ZXXKCOM20190224080904807728.doc",
                    "UpdateTime": "2019-02-24T08:23:00",
                    "AddTime": "%s"
                    },
                "eRequestArgs": {
                    "Product": 1,
                    "PlatFormType": 0,
                    "RequestSource": 0,
                    "QRCodeFee": 0.0,                           
                    "UseRMB": 1,
                    "ConsumeTime": "%s"
                },
                "eClientInfo": {
                "ClientIP": "36.110.49.98",
                "IPArea": "北京市电信",
                "UserAgent": "Mozilla_5.0__Windows_NT_10.0",
                "UserAgentMD5": "8068257D4BA0C713A0692FCCB3F228",
                "Ut": "ut-21-wQ5YX3CCbS",
                "PathInfo": null
                },
                "eViewUserIdentity": {
                    "UserID": %s,
                    "UserName": "xkw_028761111",
                    "SchoolUserID": 0
                    }
                },
            "Route": %s}'''