# Generated by Django 2.2.4 on 2019-09-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('username_role', models.CharField(max_length=32)),
                ('regTime', models.DateTimeField(null=True)),
                ('userState', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
